# Generated by Django 4.2.11 on 2024-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'title'), name='unique_title_per_blog'),
        ),
    ]
