# Generated by Django 4.2.11 on 2024-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_post_slug_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'slug'), name='unique_slug_per_blog'),
        ),
    ]
