# Generated by Django 4.2.11 on 2024-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_post_unique_slug_per_blog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_slug_per_blog',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
