# Generated by Django 4.2.11 on 2024-06-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_title_per_blog',
        ),
    ]
