# Generated by Django 4.2.11 on 2024-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_post_unique_title_per_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'title'), name='unique_title_per_blog'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'slug'), name='unique_slug_per_blog'),
        ),
    ]
