# Generated by Django 4.2.11 on 2024-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_post_slug_post_unique_title_per_blog_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_title_per_blog',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_slug_per_blog',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'title'), name='unique_title_per_blog', violation_error_message='Title already used in this blog.'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('blog', 'slug'), name='unique_slug_per_blog', violation_error_message='Slug already used in this blog.'),
        ),
    ]
